/* If you want to reset autoincrement counter in table:*/
ALTER TABLE table_name AUTO_INCREMENT = 1;

INSERT INTO airplane (name, capacity_econom, capacity_business)
VALUES
  ('TU-134',80,8),
  ('TU-154',152,24),
  ('Airbus A310',183,12),
  ('Airbus A320',149,12),
  ('Boeing-737-600',122,0),
  ('Boeing-737-700',145,12),
  ('Boeing-737-800',168,18),
  ('Boeing-737-900',192,36),
  ('Boeing-747-200',298,66);

INSERT INTO user(name, email, password_hash, registration_date)
VALUES
('Polina', 'polina@mail.ru', '827ccb0eea8a706c4c34a16891f84e7b', '2017-07-31 06:07:11'),
('TestUser', 'testuser@test.ru', '5d9c68c6c50ed3d02a2fcf54f63993b6', '2017-07-31 09:11:35');

INSERT INTO flight (airplane_id,flight_number,departure_airport_id,arrival_airport_id,
base_cost,available_places_econom,available_places_business,datetime)
VALUES
(2,'RTY-56',687 ,327,6000.00,152,24,'2017-07-25 06:07:00'),
(2,'RRY-78',687 ,327,6500.00,152,24,'2017-07-26 09:30:00'),
(3,'YTR-26',687 ,327,5500.00,183,12,'2017-07-25 12:10:00'),
(3,'NMR-91',687 ,327,5800.00,183,12,'2017-07-27 18:07:00'),
(4,'VPO-13',687 ,327,6000.00,149,12,'2017-07-28 15:30:00');


INSERT INTO airport (name, city)
VALUES ('AAE', 'Annaba'),('AAL', 'Aalborg'),('AAR', 'Aarhus'),('ABE', 'Lehigh Valley'),('ABJ', 'Abidjan'),('ABQ', 'Albuquerque'),
  ('ABZ', 'Aberdeen'),('ACA', 'Acapulco'),('ACC', 'Kotoka'),('ACE', 'Lanzarote'),('ACH', 'Altenrhein'),('ACI', 'Alderney'),('ACI', 'Channel s'),
  ('ACK', 'Nantucket'),('ACY', 'Atlantic City'),('ADA', 'Adana'),('ADB', 'Izmir'),('ADD', 'Addis Ababa'),('ADE', 'Aden'),('ADL', 'Adelaide'),
  ('ADZ', 'San Andres'),('AEP', 'Buenos Aires'),('AES', 'Alesund'),('AEX', 'Alexandria'),('AFA', 'San Rafael'),('AFW', 'Fort Worth'),('AGA', 'Agadir'),
  ('AGB', 'Augsburg'),('AGF', 'Agen'),('AGP', 'Malaga'),('AGR', 'Agra'),('AGS', 'Augusta'),('AHB', 'Abha'),('AHN', 'Athens'),('AHO', 'Alghero'),
  ('AHU', 'Al Hoceima'),('AJA', 'Ajaccio'),('AKL', 'Auckland'),('ALA', 'Almaty'),('ALB', 'Albany'),('ALC', 'Alicante'),('ALG', 'Algiers'),
  ('ALO', 'Waterloo'),('ALP', 'Aleppo'),('ALS', 'Alamosa'),('ALY', 'Alexandria'),('AMA', 'Amarillo'),('AMD', 'Ahmedabad'),('AMM', 'Amman'),
  ('AMS', 'Amsterdam'),('ANC', 'Anchorage'),('ANF', 'Antofagasta'),('ANG', 'Angoulême'),('ANR', 'Antwerp'),('AOC', 'Altenburg'),('AOI', 'Ancona'),
  ('AOR', 'Alor Setar'),('APF', 'Naples'),('APL', 'Nampula'),('APW', 'Faleolo'),('AQJ', 'Aqaba'),('ARH', 'Arkhangelsk'),('ARI', 'Arica'),('ARN', 'Stockholm'),
  ('ART', 'Watertown'),('ARW', 'Arad'),('ASB', 'Ashkabad'),('ASM', 'Asmara'),('ASP', 'Alice Springs'),('ASU', 'Asuncion'),('ASW', 'Aswan'),('ATH', 'Athens'),
  ('ATH', 'Athens'),('ATL', 'Atlanta'),('ATQ', 'Amritsar'),('ATW', 'Appleton/Outagamie County'),('AUA', 'Aruba'),('AUH', 'Abu Dhabi'),('AUS', 'Austin'),
  ('AVI', 'Ciego de Avila'),('AVL', 'Asheville'),('AVN', 'Avignon/Caumont'),('AXD', 'Alexandroupolis'),('AYT', 'Antalya'),('AZO', 'Kalamazoo/Battle Creek'),
  ('BAH', 'Bahrain'),('BAK', 'Baku'),('BAQ', 'Barranquilla'),('BAX', 'Barnaul'),('BBK', 'Kasane'),('BBS', 'Blackbushe'),('BBU', 'Bucharest'),
  ('BCN', 'Barcelona'),('BDA', 'Bermuda'),('BDL', 'Hartford'),('BDS', 'Brindisi'),('BEB', 'Benbecula'),('BEG', 'Belgrade'),('BEL', 'Belem'),
  ('BEN', 'Benghazi'),('BES', 'Brest/Guipavas'),('BEW', 'Beira'),('BEY', 'Beirut'),('BFD', 'Bradford'),('BFI', 'Boeing Field/King County'),
  ('BFM', 'Mobile Downtown'),('BFN', 'Bloemfontein'),('BFS', 'Belfast'),('BGA', 'Bucaramanga'),('BGF', 'Bangui-M´Poko'),('BGI', 'Grantley Adams'),
  ('BGM', 'Binghamton'),('BGO', 'Bergen'),('BGR', 'Bangor'),('BGY', 'Milan'),('BHD', 'Belfast City'),('BHK', 'Bukhara'),('BHM', 'Birmingham'),
  ('BHX', 'Birmingham'),('BIK', 'Biak'),('BIL', 'Billings'),('BIO', 'Bilbao'),('BIQ', 'Biarritz/Bayone/Anglet'),('BIS', 'Bismarck'),('BJL', 'Banjul'),
  ('BJM', 'Bujumbura'),('BJZ', 'Badajoz'),('BKA', 'Moscow Bykovo'),('BKI', 'Kota Kinabalu'),('BKK', 'Bangkok'),('BKO', 'Bamako'),('BLE', 'Borlänge'),
  ('BLF', 'Bluefield'),('BLI', 'Bellingham'),('BLK', 'Blackpool'),('BLL', 'Billund'),('BLQ', 'Bologna-G'),('BLR', 'Bangalore'),('BLV', 'MidAmerica'),
  ('BLZ', 'Blantyre'),('BMA', 'Stockholm'),('BMV', 'Buon Ma Thuot'),('BNA', 'Nashville'),('BNE', 'Brisbane'),('BNE', 'Brisbane'),('BNX', 'Banja Luka'),
  ('BOB', 'Bora Bora'),('BOD', 'Bordeaux/Merignac'),('BOG', 'Bogotá'),('BOH', 'Bournemouth'),('BOI', 'Boise'),('BOJ', 'Bourgas'),('BOM', 'Mumbai/Bombay'),
  ('BON', 'Flamingo'),('BOO', 'Bodø'),('BOS', 'Boston'),('BOU', 'Bourges'),('BPN', 'Balikpapan'),('BQH', 'London'),('BQN', 'Aguadilla'),
  ('BRC', 'San Carlos De Bariloche'),('BRE', 'Bremen'),('BRI', 'Bari'),('BRN', 'Bern'),('BRO', 'Brownsville/South Padre'),('BRQ', 'Brno'),('BRR', 'Barra'),
  ('BRS', 'Bristol'),('BRS', 'Bristol'),('BRU', 'Brussels'),('BSB', 'Brasilia'),('BSL', 'Basel/Mulhouse'),('BTH', 'Batam'),('BTR', 'Baton Rouge'),
  ('BTS', 'Bratislava'),('BTU', 'Bintulu'),('BTV', 'Burlington'),('BUD', 'Budapest'),('BUF', 'Buffalo'),('BUQ', 'Bulawayo'),('BUR', 'Burbank'),
  ('BVA', 'Beauvais/Tille'),('BVB', 'Boa Vista'),('BVE', 'Brive'),('BVZ', 'Brazzaville'),('BWI', 'Baltimore/Washington'),('BWK', 'Brac'),('BWN', 'Brunei'),
  ('BWU', 'Bankstown'),('BXO', 'Bissau'),('BZE', 'Belize'),('BZG', 'Bydgoszcz'),('BZN', 'Bozeman'),('BZO', 'Bolzano'),('BZR', 'Beziers/Vias'),('CAE', 'Columbia'),
  ('CAI', 'Cairo'),('CAK', 'Akron'),('CAL', 'Campbeltown'),('CAN', 'Guangzhou Baiyun'),('CAX', 'Carlisle'),('CAY', 'Cayenne'),('CBB', 'Cochabamba-J'),
  ('CBE', 'Cumberland'),('CBG', 'Cambridge'),('CBN', 'Canberra'),('CCF', 'Carcassonne'),('CCJ', 'Calicut'),('CCK', 'Cocos s'),('CCP', 'Concepcion'),
  ('CCS', 'Caracas'),('CCU', 'Kolkata'),('CDG', 'Paris'),('CDU', 'Camden'),('CEG', 'Chester'),('CEI', 'Chiang Rai'),('CEK', 'Chelyabinsk'),('CEN', 'Ciudad'),
  ('CEQ', 'Cannes'),('CER', 'Cherbourg'),('CEZ', 'Cortez'),('CFE', 'Clermont'),('CFG', 'Cienfuegos'),('CFN', 'Donegal'),('CFU', 'Corfu'),('CGB', 'Cuiaba'),
  ('CGH', 'São Paulo'),('CGK', 'Jakarta'),('CGN', 'Cologne/Bonn'),('CGP', 'Chittagong'),('CGR', 'Campo Grande'),('CHA', 'Chattanooga'),('CHC', 'Christchurch'),
  ('CHN', 'Cheongju'),('CHQ', 'Chania'),('CHR', 'Châteauroux/Déols'),('CIA', 'Rome'),('CID', 'Eastern Iowa'),('CJB', 'Coimbatore'),('CJC', 'Calama'),('CJU', 'Jeju'),
  ('CKY', 'Conakry'),('CLE', 'Cleveland'),('CLM', 'Port Angeles'),('CLO', 'Cali'),('CLQ', 'Colima'),('CLT', 'Charlotte/Douglas'),('CLX', 'Lima'),('CLY', 'Calvi'),
  ('CMB', 'Bandaranaike'),('CME', 'Ciudad del Carmen'),('CMF', 'Chambery/Aix les Bains'),('CMG', 'Corumba'),('CMH', 'Columbus'),('CMI', 'Champaign'),
  ('CMN', 'Casablanca'),('CMR', 'Colmar'),('CMW', 'Camagüey'),('CND', 'Constanta'),('CNF', 'Belo Horizonte'),('CNS', 'Cairns'),('CNX', 'Chiang Mai'),
  ('COK', 'Cochin'),('COO', 'Cotonou Cadjehoun'),('COR', 'Cordoba'),('COS', 'Colorado Springs'),('CPE', 'Campeche'),('CPH', 'Copenhagen'),('CPO', 'Copiapó'),
  ('CPR', 'Casper/Natrona County'),('CPT', 'Cape Town'),('CRD', 'Comodoro Rivadavia'),('CRK', 'Cork'),('CRL', 'Brussels'),('CRP', 'Corpus Christi'),
  ('CRV', 'Crotone'),('CRW', 'Charleston'),('CTA', 'Catania'),('CTC', 'Catamarca'),('CTG', 'Cartagena'),('CTM', 'Chetumal'),('CTU', 'Chengdu/Shuangliu'),
  ('CUF', 'Cuneo'),('CUN', 'Cancun'),('CUR', 'Curacao'),('CVG', 'Cincinnati/N Kentucky'),('CVJ', 'Cuernavaca'),('CVM', 'Ciudad Victoria'),('CVT', 'Coventry'),
  ('CWA', 'Wausau/Central Wisconsin'),('CWB', 'Curitiba'),('CWL', 'Cardiff'),('CYB', 'Gerrard Smith'),('CYO', 'Cayo Largo'),('CYS', 'Cheyenne'),
  ('CZL', 'Constantine'),('CZM', 'Cozumel'),('CZS', 'Cruzeiro do Sul'),('DAB', 'Daytona Beach'),('DAC', 'Dhaka'),('DAD', 'Da Nang'),('DAL', 'Dallas Love Field'),
  ('DAM', 'Damascus'),('DAR', 'Dar-es'),('DAY', 'Dayton'),('DBQ', 'Dubuque'),('DBV', 'Dubrovnik'),('DCA', 'Washington'),('DCF', 'Canefield'),('DCM', 'Castres'),
  ('DEC', 'Decatur'),('DEL', 'Delhi'),('DEN', 'Denver'),('DET', 'Detroit City'),('DFW', 'Dallas/Fort Worth'),('DHA', 'Dhahran'),('DHN', 'Dothan'),
  ('DIJ', 'Dijon'),('DIL', 'Dili'),('DJE', 'Djerba'),('DKR', 'Dakar'),('DLA', 'Douala'),('DLC', 'Dalian'),('DLD', 'Geilo'),('DLE', 'Dole/Tavaux'),
  ('DLM', 'Dalaman'),('DME', 'Moscow Domodedovo'),('DMM', 'Dammam'),('DND', 'Dundee'),('DNK', 'Dnepropetrovsk'),('DNR', 'Dinard/Plertuit/St Malo'),
  ('DOH', 'Doha'),('DOL', 'Deauville/Saint Gatien'),('DOM', 'Melville Hall'),('DOT', 'Buenos Aires'),('DPS', 'Bali'),('DRO', 'Durango'),('DRS', 'Dresden'),
  ('DRW', 'Darwin'),('DSA', 'Doncaster'),('DSM', 'Des Moines'),('DTM', 'Dortmund'),('DTP', 'Pittsburgh'),('DTW', 'Detroit'),('DUB', 'Dublin'),
  ('DUD', 'Dunedin'),('DUJ', 'Dubois'),('DUR', 'Durban'),('DUS', 'Düsseldorf'),('DVO', 'Davao'),('DXB', 'Dubai'),('DYU', 'Dushanbe'),('EAS', 'San Sebastian'),
  ('EAT', 'Wenatchee/Pangborn'),('EBB', 'Entebbe'),('EBJ', 'Esbjerg'),('EBU', 'Saint Etienne'),('ECN', 'Ercan'),('EDI', 'Edinburgh'),('EDL', 'Eldoret'),
  ('EFD', 'Houston'),('EFL', 'Kefallinia'),('EGC', 'Bergerac'),('EGS', 'Egilsstadir'),('EIN', 'Eindhoven'),('ELM', 'Elmira/Coring'),('ELP', 'El Paso'),
  ('ELQ', 'Gassim'),('ELS', 'East London'),('EMA', 'Nottingham'),('ENC', 'Nancy/Essey'),('ENF', 'Enontekiö'),('ENS', 'Enschede'),('EOI', 'Orkney Is'),
  ('EPL', 'Epinal/Mirecourt'),('EQS', 'Esquel'),('ERF', 'Erfurt'),('ERH', 'Errachidia'),('ERI', 'Erie'),('ESB', 'Ankara'),('ESF', 'Alexandria'),
  ('ESH', 'Shoreham'),('ESS', 'Essen/Mülheim'),('ESU', 'Essaouira Mogador'),('ETH', 'Eilat-J Hozman'),('ETZ', 'Metz/Nancy/Lorraine'),('EUN', 'Laayoune Hassan'),
  ('EVE', 'Harstad/Narvik'),('EVN', 'Yerevan'),('EVV', 'Evansville'),('EWR', 'Newark'),('EXT', 'Exeter'),('EYW', 'Key West'),('EZE', 'Buenos Aires'),
  ('FAA', 'Faranah'),('FAB', 'Farnborough'),('FAE', 'Vagar'),('FAI', 'Fairbanks'),('FAO', 'Faro'),('FAR', 'Fargo'),('FAT', 'Fresno Yosemite'),
  ('FAY', 'Fayetteville'),('FCN', 'Cuxhaven/Nordholz Sea'),('FCO', 'Rome'),('FDF', 'Martinique'),('FDH', 'Friedrichshafen/Lowental'),('FDO', 'San Fernando'),
  ('FEZ', 'Fes Saiss'),('FIA', 'Kortrijk/Flanders'),('FIH', 'Kinshasa-N´Djili'),('FJR', 'Fujairah'),('FKB', 'Karlsruhe/Baden'),('FKJ', 'Fukui'),
  ('FLG', 'Flagstaff Pulliam'),('FLL', 'Fort Lauderdale'),('FLN', 'Florianópolis'),('FLO', 'Florence'),('FLR', 'Florence'),('FLW', 'Flores'),
  ('FMA', 'Formosa'),('FNA', 'Freetown'),('FNC', 'Funchal'),('FNI', 'Nimes/Arles/Camargue'),('FNJ', 'P´yongyang'),('FNL', 'Fort Collins'),
  ('FNT', 'Flint'),('FOR', 'Fortaleza'),('FPO', 'Grand Bahama'),('FPR', 'Fort Pierce'),('FRA', 'Frankfurt'),('FRL', 'Forli'),('FRU', 'Bishkek'),
  ('FRW', 'Francistown'),('FSC', 'Figari Sud Corse'),('FSD', 'Joe Foss Field'),('FSM', 'Fort Smith'),('FUE', 'Fuerteventura'),('FUK', 'Fukuoka'),
  ('FUN', 'Funafuti'),('FWA', 'Fort Wayne'),('FYM', 'Fayetteville'),('GAF', 'Gafsa'),('GAU', 'Guwahati'),('GAY', 'Gaya'),('GBE', 'Gaborone'),
  ('GCI', 'Channel s'),('GCM', 'Grand Cayman'),('GDL', 'Guadalajarra Hidalgo'),('GDN', 'Gdansk Lech Walesa'),('GDT', 'Grand Turk'),('GDX', 'Magadan Sokol'),
  ('GEG', 'Spokane'),('GEN', 'Oslo'),('GEO', 'Georgetown'),('GFK', 'Grand Forks'),('GIB', 'Gibraltar'),('GIG', 'Rio de Janeiro'),('GIZ', 'Gizan'),
  ('GJT', 'Grand Junction'),('GLA', 'Glasgow'),('GLE', 'Gainesville'),('GLO', 'Gloucestershire'),('GME', 'Gomel (Pokalubichi)'),('GMZ', 'La Gomera'),
  ('GNA', 'Grodno (Obukhovo)'),('GNB', 'Grenoble/Saint'),('GND', 'Grenada'),('GOA', 'Genoa'),('GOI', 'Goa'),('GOJ', 'Nizhny Novgorod'),('GOT', 'Göteborg'),
  ('GOU', 'Garoua'),('GOZ', 'Gorna Oryahovica'),('GPA', 'Patras/Araxos'),('GPO', 'General Pico'),('GPT', 'Gulfport'),('GPZ', 'Grand Rapids/Kent County'),
  ('GRJ', 'George'),('GRO', 'Gerona'),('GRQ', 'Groningen'),('GRU', 'São Paulo'),('GRX', 'Granada'),('GRZ', 'Graz'),('GSE', 'Göteborg City'),('GSO', 'Piedmont Triad'),
  ('GSP', 'Greenville Spartanburg'),('GTF', 'Great Falls'),('GTR', 'Columbus'),('GUA', 'Guatemala City'),('GUM', 'Guam Pat'),('GUW', 'Atyrau'),('GVA', 'Geneva'),
  ('GWT', 'Westerland Flughafen'),('GWY', 'Galway'),('GYE', 'Guayaquil'),('GYM', 'Guaymas'),('GYN', 'Goiania'),('GYY', 'Chicago'),('GZA', 'Gaza'),('HAH', 'Moroni'),
  ('HAJ', 'Hannover'),('HAM', 'Hamburg'),('HAN', 'Hanoi'),('HAR', 'Harrisburg'),('HAU', 'Haugesund'),('HAV', 'La Havana'),('HAW', 'Haverfordwest'),('HBA', 'Hobart'),
  ('HDY', 'Hat Yai'),('HEA', 'Herat'),('HEL', 'Helsinki'),('HEM', 'Helsinki'),('HER', 'Heraklion'),('HFA', 'Haifa'),('HGR', 'Hagerstown'),('HHH', 'Hilton Head'),
  ('HHN', 'Frankfurt'),('HIJ', 'Hiroshima'),('HIR', 'Henderson'),('HJR', 'Khajuraho'),('HKG', 'Hong Kong'),('HKT', 'Phuket'),('HKY', 'Hickory'),('HLA', 'Lanseria'),
  ('HLP', 'Jakarta'),('HNL', 'Honolulu'),('HNT', 'Tokyo'),('HOG', 'Holguin'),('HOO', 'Hof'),('HOR', 'Horta'),('HOU', 'Houston'),('HPN', 'Westchester County'),
  ('HRB', 'Harbin'),('HRE', 'Harare'),('HRG', 'Hurgadah'),('HSI', 'Hastings'),('HSV', 'Huntsville'),('HTS', 'Huntington Tri'),('HUH', 'Huahine'),
  ('HUY', 'Humberside'),('HVN', 'New Haven'),('HYD', 'Hyderabad'),('IAD', 'Washington'),('IAH', 'Houston'),('IBZ', 'Ibiza'),('ICN', 'Seoul'),('ICT', 'Wichita Mid'),
  ('IDY', 'Ile d´Yeu'),('IEV', 'Kiev'),('IGR', 'Iguazu'),('IGU', 'Foz do Iguaçu'),('IKT', 'Irkutsk'),('ILM', 'Wilmington'),('ILY', 'Islay'),('IND', 'napolis'),
  ('IND', 'napolis'),('INN', 'Innsbruck'),('INT', 'Winston'),('INU', 'Nauru'),('INV', 'Inverness'),('IOA', 'Ioannina'),('IOM', 'Isle of Man'),('IPH', 'Ipoh'),
  ('IPT', 'Williamsport'),('IQQ', 'Iquique'),('IQT', 'Iquitos'),('IRJ', 'La Rioja'),('ISA', 'Mount Isa'),('ISB', 'Islamabad'),('ISC', 'Isles of Scilly´s'),
  ('ISO', 'Kinston'),('ISP', 'Long'),('IST', 'Istanbul'),('ITH', 'Ithaca'),('ITM', 'Osaka'),('ITO', 'Hilo'),('IVL', 'Ivalo'),('IWA', 'Williams Gateway'),
  ('IYK', 'Inyokern'),('JAA', 'Jalalabad'),('JAC', 'Jackson Hole'),('JAI', 'Jaipur'),('JAN', 'Jackson'),('JAX', 'Jacksonville'),('JED', 'Jeddah'),
  ('JER', 'Channel'),('JFK', 'New York'),('JHB', 'Johor Bahru'),('JIB', 'Djibouti'),('JKJ', 'Jönköping'),('JNB', 'Johannesburg'),('JOE', 'Joensuu'),
  ('JOG', 'Yogyakarta'),('JOI', 'Joinville'),('JRO', 'Kilimanjaro'),('JST', 'Johnstown'),('JYV', 'Jyvaskyla'),('KAB', 'Kariba'),('KAJ', 'Kajaani'),
  ('KAN', 'Kano'),('KAO', 'Kuusamo'),('KBL', 'Kabul'),('KBP', 'Kiev'),('KBR', 'Kota Bharu'),('KCH', 'Kuching'),('KCZ', 'Kochi'),('KDH', 'Kandahar'),
  ('KDL', 'Kärdla'),('KEF', 'Keflavik'),('KEM', 'Kemi'),('KGF', 'Karaganda'),('KGJ', 'Karonga'),('KGL', 'Kigali'),('KGS', 'Kos'),('KHH', 'Kaohsiung'),
  ('KHI', 'Karachi'),('KHI', 'Karachi'),('KHV', 'Khabarovsk'),('KID', 'Kristianstad'),('KIJ', 'Niigata'),('KIM', 'Kimberley'),('KIN', 'Kingston'),('KIR', 'Kerry'),
  ('KIS', 'Kisumu'),('KIV', 'Chisinau'),('KIX', 'Osaka'),('KJA', 'Krasnoyarsk'),('KKC', 'Khon Kaen'),('KKN', 'Kirkenes'),('KLR', 'Kalmar'),('KLU', 'Klagenfurt'),
  ('KLV', 'Karlovy Vary'),('KLX', 'Kalamata'),('KMG', 'Kunming'),('KMI', 'Miyazaki'),('KMJ', 'Kumamoto'),('KMQ', 'Komatsu'),('KMS', 'Kumasi'),('KOA', 'Kona'),
  ('KOI', 'Kirkwall'),('KOK', 'Kruunupyy'),('KRK', 'Krakow'),('KRN', 'Kiruna'),('KRP', 'Karup'),('KRS', 'Kjevik'),('KRT', 'Khartoum'),('KSC', 'Kosice'),
  ('KSF', 'Kassel'),('KSO', 'Kastoria'),('KTM', 'Kathmandu'),('KTT', 'Kittilä'),('KTW', 'Katowice'),('KUA', 'Kuantan'),('KUL', 'Kuala'),('KUN', 'Kaunas'),
  ('KUO', 'Kuopio'),('KVA', 'Kavala'),('KWG', 'Krivij Rig'),('KWI', 'Kuwait'),('KWJ', 'Gwangju'),('KZN', 'Kazan'),('LAD', 'Luanda'),('LAE', 'Lae'),
  ('LAI', 'Lannion'),('LAN', 'Lansing'),('LAP', 'La Paz Leon'),('LAS', 'Las Vegas'),('LAX', 'Los Angeles'),('LBA', 'Leeds Bradford'),('LBB', 'Lubbock'),
  ('LBC', 'Luebeck'),('LBF', 'North Platte'),('LBG', 'Le Bourget'),('LBI', 'Albi'),('LBQ', 'Lambarene'),('LBU', 'Labuan'),('LBV', 'Libreville´Ba'),
  ('LCA', 'Larnaca'),('LCE', 'La Ceiba'),('LCG', 'La Coruña'),('LCJ', 'Lodz'),('LCK', 'Rickenbacker'),('LCY', 'London City'),('LDE', 'Tarbes'),
  ('LDU', 'Lahad Datu'),('LDY', 'City of Derry'),('LED', 'St Petersburg'),('LEH', 'Le Havre/Octeville'),('LEI', 'Almeria'),('LEJ', 'Leipzig/Halle'),
  ('LEK', 'Labe'),('LEQ', 'Land´s End'),('LEX', 'Lexington/Blue Grass'),('LEY', 'Lelystad'),('LFT', 'Lafayette'),('LFW', 'Lome'),('LGA', 'New York'),
  ('LGB', 'Long Beach'),('LGC', 'León'),('LGG', 'Liège'),('LGK', 'Langkawi'),('LGS', 'Malargue'),('LGW', 'London'),('LHA', 'Lahr'),('LHE', 'Lahore'),
  ('LIG', 'Limoges/Bellegarde'),('LIH', 'Lihue'),('LIL', 'Lille'),('LIN', 'Milan'),('LIS', 'Lisbon'),('LIT', 'Little Rock'),('LJU', 'Ljubljana'),
  ('LKL', 'Lakselv'),('LKO', 'Lucknow'),('LLA', 'Luleå'),('LLW', 'Lilongwe'),('LMH', 'Limon'),('LMT', 'Klamath Falls'),('LNS', 'Lancaster'),('LNZ', 'Linz'),
  ('LOS', 'Lagos'),('LPA', 'Gran Canaria'),('LPB', 'La Paz'),('LPL', 'Liverpool'),('LPP', 'Lappeenranta'),('LPR', 'Lorain County'),('LPX', 'Liepaja'),
  ('LRD', 'Laredo'),('LRH', 'La Rochelle'),('LRT', 'Lorient/Lann'),('LSC', 'La Serena'),('LSE', 'La Crosse'),('LSI', 'Shetland'),('LST', 'Launceston'),
  ('LTN', 'London'),('LTQ', 'Le Touquet'),('LTT', 'St Tropez'),('LUG', 'Lugano'),('LUN', 'Lusaka'),('LUX', 'Luxembourg'),('LVI', 'Livingstone'),('LWN', 'Gyumri'),
  ('LXR', 'Luxor'),('LXS', 'Limnos'),('LYH', 'Lynchburg'),('LYN', 'Lyon/Bron'),('LYR', 'Svalbard'),('LYS', 'Lyon'),('LYX', 'London Ashford'),
  ('MAA', 'Chennai/Madras'),('MAD', 'Madrid'),('MAF', 'Midland'),('MAH', 'Menorca'),('MAM', 'Matamoros'),('MAN', 'Manchester'),('MAO', 'Manaus'),
  ('MBA', 'Mombasa'),('MBJ', 'Montego Bay'),('MBW', 'Moorabbin'),('MBX', 'Maribor'),('MCI', 'Kansas City'),('MCM', 'Monaco Heliport'),('MCO', 'Orlando'),
  ('MCT', 'Muscat'),('MCV', 'Madrid'),('MCW', 'Mason City'),('MCZ', 'Maceio'),('MDC', 'Manado'),('MDE', 'Medellin'),('MDK', 'Mbandaka'),('MDL', 'Mandalay'),
  ('MDQ', 'Mar Del Plata'),('MDW', 'Chicago Midway'),('MDZ', 'Mendoza'),('MEB', 'Essendon'),('MED', 'Madinah'),('MEI', 'Meridian'),('MEL', 'Melbourne'),
  ('MEM', 'Memphis'),('MES', 'Medan'),('MFE', 'McAllen'),('MFM', 'Macau'),('MFU', 'Mfuwe'),('MGA', 'Managua'),('MGL', 'Flughafen Düsseldorf'),
  ('MGQ', 'Mogadishu'),('MHQ', 'Mariehamn'),('MHT', 'Manchester'),('MIA', 'Miami'),('MID', 'Merida'),('MIK', 'Mikkeli City'),('MIR', 'Monastir'),
  ('MJT', 'Mitilini'),('MJV', 'Murcia'),('MKC', 'Kansas City'),('MKE', 'Milwaukee'),('MKW', 'Penta'),('MKY', 'Mackay'),('MKZ', 'Melaka'),('MLA', 'Malta'),
  ('MLB', 'Melbourne'),('MLE', 'Male'),('MLH', 'Basel/Mulhouse'),('MLN', 'Melilla'),('MLZ', 'Melo'),('MME', 'Durham Tees Valley'),('MMJ', 'Matsumoto'),
  ('MMK', 'Murmansk'),('MMX', 'Malmö'),('MNI', 'Montserrat'),('MNL', 'Manila'),('MOB', 'Mobile'),('MOD', 'Modesto City'),('MOL', 'Molde'),('MOT', 'Minot'),
  ('MOZ', 'Moorea'),('MPL', 'Montpellier'),('MPM', 'Maputo'),('MRS', 'Marseille/Provence'),('MRU', 'Sir Seewoosagur Ramgoolam'),('MSE', 'Kent'),
  ('MSJ', 'Misawa'),('MSN', 'Dane County'),('MSO', 'Missoula'),('MSP', 'Minneapolis'),('MSQ', 'Minsk'),('MSR', 'Münster'),('MST', 'Maastricht Aachen'),
  ('MSU', 'Maseru'),('MSY', 'New Orleans'),('MTH', 'Marathon'),('MTS', 'Manzini'),('MTY', 'Monterrey'),('MUB', 'Maun'),('MUC', 'Munich'),
  ('MUD', 'Montevideo'),('MVB', 'Ville'),('MWH', 'Grant County'),('MXP', 'Milan'),('MXX', 'Mora'),('MYY', 'Miri'),('MZO', 'Manzanillo'),
  ('MZR', 'Mazar I Sharif'),('MZT', 'Mazatlan'),('NAN', 'Fiji'),('NAP', 'Naples'),('NAS', 'Nassau'),('NAT', 'Natal'),('NBO', 'Nairobi'),
  ('NCA', 'North Caicos'),('NCE', 'Nice/Cote D´Azur'),('NCH', 'Baucau'),('NCL', 'Newcastle'),('NCY', 'Annecy'),('NDB', 'Nouadhibou'),('NDH', 'N´Djamena'),
  ('NDR', 'Nador'),('NEV', 'Nevis'),('NGO', 'Nagoya'),('NGS', 'Nagasaki'),('NIM', 'Niamey Diori Hamani'),('NKG', 'Nanjing Lukou'),('NKO', 'Nouakchott'),
  ('NLA', 'Ndola and Kitwe'),('NLD', 'Nuevo Laredo'),('NLV', 'Nikolaev'),('NOC', 'Knock'),('NOG', 'Nogales'),('NOP', 'Mactan'),('NOU', 'New Caledonia'),
  ('NQY', 'Newquay Cornwall'),('NRK', 'Norrköping'),('NRL', 'Orkney Is'),('NRR', 'Roosevelt Roads'),('NRT', 'Tokyo'),('NSI', 'Yaounde'),('NSK', 'Norilsk'),
  ('NTE', 'Nantes'),('NTL', 'Newcastle'),('NTY', 'Pilanesburg'),('NUE', 'Nuremberg'),('NVT', 'Navegantes'),('NWI', 'Norwich'),('NYI', 'Sunyani'),
  ('NYO', 'Stockholm'),('OAK', 'Oakland'),('OAX', 'Oaxaca'),('ODB', 'Cordoba'),('ODE', 'Odense'),('ODS', 'Odessa'),('OER', 'Örnsköldsvik'),('OGG', 'Kahului'),
  ('OHD', 'Ohrid'),('OKA', 'Okinawa/Naha'),('OKC', 'Oklahoma City'),('OKJ', 'Okayama'),('OLB', 'Olbia'),('OMA', 'Omaha'),('OMO', 'Mostar'),('ONT', 'Ontario'),
  ('OOL', 'Coolangatta'),('OPO', 'Oporto'),('ORB', 'Örebro'),('ORD', 'Chicago - O´Hare'),('ORF', 'Norfolk'),('ORH', 'Worcester'),('ORY', 'Paris'),
  ('OSD', 'Östersund'),('OSI', 'Osijek'),('OSL', 'Letiste'),('OSR', 'Ostrava'),('OST', 'Ostend/Bruges'),('OTP', 'Bucharest'),('OUA', 'Ouagadougou'),
  ('OUD', 'Oujda Angads'),('OUL', 'Oulu'),('OVB', 'Novosibirsk'),('OVD', 'Asturias'),('OXF', 'Oxford'),('OZZ', 'Ouarzazate'),('PAD', 'Paderborn/Lippstadt'),
  ('PAP', 'Port-au'),('PAT', 'Patna'),('PAZ', 'Poza Rica'),('PBC', 'Puebla'),('PBG', 'Plattsburgh'),('PBH', 'Paro'),('PBI', 'Palm Beach'),
  ('PBM', 'Paramarib'),('PDG', 'Padang'),('PDL', 'Ponta Delgada'),('PDT', 'Pendleton/Eastern Oregon'),('PDV', 'Plovdiv'),('PDX', 'Portland'),
  ('PED', 'Pardubice'),('PEI', 'Pereira'),('PEK', 'Beijing'),('PEN', 'Penang'),('PER', 'Perth'),('PEW', 'Peshawar'),('PFN', 'Panama City/Bay County'),
  ('PFO', 'Paphos'),('PGF', 'Perpignan/Rivesaltes'),('PHC', 'Port Harcourt'),('PHL', 'Philadelphia'),('PHX', 'Phoenix Sky Harbor'),('PIA', 'Peoria'),
  ('PIE', 'St Petersburg'),('PIK', 'Glasgow Prestwick'),('PIS', 'Poitiers'),('PIU', 'Piura'),('PKB', 'Parkersburg'),('PKC', 'Petropavlovsk'),
  ('PKU', 'Pekanbaru'),('PKW', 'Selebi Phikwe'),('PLB', 'Plattsburgh'),('PLH', 'Plymouth City'),('PLM', 'Palembang'),('PLQ', 'Palanga'),
  ('PLS', 'Providenciales'),('PLU', 'Belo Horizonte'),('PLZ', 'Port Elizabeth'),('PMC', 'Puerto Montt'),('PMG', 'Ponta Pora'),('PMI', 'Palma De Mallorca'),
  ('PMO', 'Palermo'),('PMY', 'Puerto Madryn'),('PNA', 'Pamplona'),('PNH', 'Phnom Penh'),('PNK', 'Pontianak'),('PNR', 'Pointe'),('PNS', 'Pensacola'),
  ('POA', 'Porto Alegre'),('POG', 'Port Gentil'),('POM', 'Port Moresby'),('POP', 'Puerto Plata'),('POR', 'Pori'),('POS', 'Piarco'),('POU', 'Poughkeepsie'),
  ('POW', 'Aerodrom Portoroz'),('POX', 'Paris'),('POZ', 'Poznan'),('PPG', 'Pago Pago'),('PPT', 'Tahiti ´a'),('PQI', 'Northern Maine'),('PRA', 'Parana'),
  ('PRA', 'Prana'),('PRG', 'Prague'),('PSA', 'Pisa'),('PSE', 'Mercedita'),('PSP', 'Palm Springs'),('PSR', 'Pescara'),('PSS', 'Posadas'),('PTP', 'Point-a Raizet'),
  ('PTY', 'Panama City'),('PUF', 'Pau'),('PUQ', 'Punta Arenas'),('PUS', 'Pusan'),('PUY', 'Pula'),('PVC', 'Provincetown'),('PVD', 'Providence Green'),
  ('PVG', 'Shanghai'),('PVR', 'Puerto Vallarta'),('PXO', 'Porto Santo'),('PZE', 'Penzance Heliport'),('PZY', 'Piestany'),('QGY', 'Gyõr'),('QRO', 'Querétaro'),
  ('QSA', 'Sabadell'),('RAB', 'Rabaul'),('RAH', 'Rafha'),('RAK', 'Marrakech'),('RAO', 'Ribeirao Preto'),('RAP', 'Rapid City'),('RAR', 'Cook Is'),('RBA', 'Rabat'),
  ('RBR', 'Rio Branco'),('RCQ', 'Reconquista'),('RCU', 'Rio Cuarto'),('RDG', 'Reading'),('RDM', 'Redmond'),('RDU', 'Raleigh'),('RDZ', 'Rodez/Marcillac'),
  ('REC', 'Recife /Gilberto'),('REK', 'Reykjavik'),('REP', 'Siem Reap'),('RES', 'Resistencia'),('REU', 'Reus'),('RFD', 'Rockford'),('RFP', 'Reiatea'),
  ('RGA', 'Rio Grande'),('RGL', 'Rio Gallegos'),('RGN', 'Yangon'),('RHE', 'Reims/Champagne'),('RHI', 'Rhinelander'),('RHQ', 'Rhodes'),('RIC', 'Richmond'),
  ('RIV', 'Greater Los Angeles'),('RIX', 'Riga'),('RJK', 'Rijeka'),('RKE', 'Copenhagen'),('RKT', 'Ras Al Khaimah'),('RLG', 'Rostock'),('RMI', 'Rimini'),
  ('RNN', 'Bornholm'),('RNO', 'Reno/Tahoe'),('RNS', 'Rennes/Saint'),('ROA', 'Roanoke'),('ROB', 'Monrovia'),('ROB', 'Monrovia'),('ROC', 'Greater Rochester'),
  ('ROP', 'Rota'),('ROW', 'Roswell'),('RPN', 'Rosh Pina'),('RRG', 'Plaine Corail'),('RSA', 'Santa Rosa'),('RSD', 'Rock Sound'),('RST', 'Rochester'),
  ('RSW', 'Fort Myers'),('RTM', 'Rotterdam'),('RTW', 'Saratov'),('RUH', 'Riyadh'),('RUN', 'Saint'),('RVN', 'Rovaniemi'),('RWI', 'Rocky Mount/Wilson'),
  ('RWN', 'Rivne'),('RZE', 'Rzeszow'),('SAH', 'Sana´a'),('SAN', 'San Diego'),('SAP', 'San Pedro Sula'),('SAT', 'San Antonio'),('SAV', 'Savannah'),
  ('SAW', 'Istanbul'),('SBA', 'Santa Barbara'),('SBK', 'Saint Brieuc'),('SBN', 'South Bend'),('SBP', 'San Luis County'),('SBW', 'Sibu'),
  ('SBY', 'Salisbury/Ocean City'),('SCE', 'State College'),('SCL', 'Santiago'),('SCN', 'Saarbrucken'),('SCQ', 'Santiago'),('SCU', 'Santiago'),
  ('SDA', 'Baghdad'),('SDE', 'Santiago del Estero'),('SDF', 'Louisville'),('SDI', 'Santiago'),('SDJ', 'Sendai'),('SDK', 'Sandakan'),('SDL', 'Sundsvall'),
  ('SDQ', 'Santo Domingo'),('SDR', 'Santander'),('SDU', 'Rio de Janeiro'),('SDV', 'Tel Aviv'),('SDY', 'Sidney'),('SEA', 'Seattle/Tacoma'),('SEB', 'Sebha'),
  ('SEL', 'Seoul'),('SEN', 'London'),('SEZ', 'Seychelles'),('SFA', 'Sfax'),('SFB', 'Orlando Sanford'),('SFG', 'Grande Case ´Esperance'),
  ('SFJ', 'Sondre Stromfjord/Kangerlussuaq'),('SFO', 'San Francisco'),('SGD', 'Sønderborg'),('SGN', 'Ho Chi Minh City'),('SHA', 'Shanghai'),('SHE', 'Shenyang'),
  ('SHJ', 'Sharjah'),('SHV', 'Shreveport'),('SID', 'Amilcar Cabral'),('SIN', 'Singapore'),('SIR', 'Sion'),('SJC', 'San Jose'),('SJF', 'Antigua'),('SJJ', 'Sarajevo'),
  ('SJO', 'San Jose'),('SJT', 'San Angelo'),('SJU', 'San Juan'),('SJY', 'Seinäjoki'),('SKB', 'Saint Kitts'),('SKD', 'Samarkand'),('SKG', 'Makedonia'),
  ('SKP', 'Skopje'),('SKS', 'Vojens'),('SKT', 'Sialkot'),('SLA', 'Salta'),('SLC', 'Salt Lake City'),('SLD', 'Sliac'),('SLK', 'Saranac Lake'),
  ('SLL', 'Salalah Oman'),('SLM', 'Salamanca'),('SLN', 'Salina'),('SLU', 'Castries'),('SLU', 'Saint Lucia'),('SLX', 'South Caicos'),('SMA', 'Santa Maria'),
  ('SMF', 'Sacramento County'),('SMI', 'Samos'),('SMV', 'St Moritz'),('SNA', 'Santa Ana'),('SNN', 'Shannon'),('SNR', 'St Nazaire'),('SOC', 'Surakarta'),
  ('SOF', 'Sofia'),('SOU', 'Southampton'),('SPC', 'La Palma'),('SPN', 'Saipan'),('SPU', 'Split'),('SQW', 'Skive'),('SRP', 'Stord'),('SRQ', 'Sarasota'),
  ('SSA', 'Salvador'),('SSG', 'Malabo'),('STA', 'Stauning Vestjyllands'),('STL', 'Saint Louis'),('STM', 'Santarém'),('STN', 'London'),('STR', 'Stuttgart'),
  ('STT', 'Saint Thomas King'),('STX', 'Saint Croix'),('SUB', 'Surabaya'),('SUF', 'Lamezia'),('SUJ', 'Satu Mare'),('SUV', 'Fiji'),('SUX', 'Sioux Gateway'),
  ('SVD', 'Saint Vincent'),('SVG', 'Stavanger'),('SVL', 'Savonlinna'),('SVO', 'Moscow Sheremetyevo'),('SVQ', 'Seville'),('SVX', 'Ekaterinburg'),
  ('SWF', 'Stewart'),('SWS', 'Swansea'),('SXB', 'Strasbourg'),('SXF', 'Berlin'),('SXL', 'Sligo'),('SXM', 'Saint Maarten'),('SYD', 'Sydney'),('SYQ', 'San José'),
  ('SYR', 'Syracuse'),('SYX', 'Sanya'),('SYY', 'Stornoway'),('SYZ', 'Shiraz'),('SZB', 'Kuala'),('SZD', 'Sheffield City'),('SZG', 'Salzburg'),
  ('SZW', 'Schwerin Parchim'),('SZX', 'Shenzhen'),('SZZ', 'Szczecin'),('TAB', 'Crown Point'),('TAE', 'Daegu'),('TAS', 'Tashkent'),('TAT', 'Poprad'),
  ('TAY', 'Tartu'),('TBJ', 'Tabarka'),('TBS', 'Tbilisi'),('TBU', 'Fua´amotu'),('TCA', 'Tennant Creek'),('TCE', 'Tulcea'),('TCN', 'Tehuacán'),('TED', 'Thisted'),
  ('TFN', 'Tenerife North'),('TFS', 'Tenerife South'),('TGG', 'Kuala Terengganu'),('TGM', 'Targu Mures'),('TGT', 'Tanga'),('TGU', 'Tegucigalpa'),
  ('TGZ', 'Tuxtla Gutiérrez'),('THF', 'Berlin'),('THR', 'Tehran'),('TIA', 'Tirana'),('TIF', 'Taif'),('TIP', 'Tripoli'),('TIQ', 'West Tinian'),('TJM', 'Tyumen'),
  ('TLC', 'Toluca'),('TLL', 'Tallinn'),('TLN', 'Toulon/Hyeres'),('TLS', 'Toulouse'),('TLV', 'Tel Aviv'),('TML', 'Tamale'),('TMP', 'Tampere'),
  ('TMR', 'Tamanrasset'),('TMS', 'Sao Tome'),('TNG', 'Tangier'),('TNJ', 'Tanjung Pinang'),('TNR', 'Antananarivo'),('TOE', 'Tozeur'),('TOL', 'Toledo Express'),
  ('TOS', 'Tromsø'),('TOY', 'Toyama'),('TPA', 'Tampa'),('TPE', 'Taipei'),('TPQ', 'Tepic'),('TRD', 'Trondheim/Vaernes'),('TRE', 'Tiree'),
  ('TRF', 'Sandefjord'),('TRI', 'Tri'),('TRK', 'Turku'),('TRN', 'Turin'),('TRS', 'Trieste'),('TRV', 'Thiruvanthapuram'),('TRV', 'Trivandrum'),
  ('TRW', 'Bonriki'),('TRZ', 'Tiruchirapalli'),('TSF', 'Treviso'),('TSN', 'Tianjin'),('TSR', 'Timisoara'),('TSV', 'Townsville'),('TTA', 'Tan Tan'),
  ('TTN', 'Trenton'),('TUC', 'Tucuman'),('TUL', 'Tulsa'),('TUN', 'Tunis'),('TUS', 'Tucson'),('TUU', 'Tabuk'),('TVL', 'Lake Tahoe'),('TWU', 'Tawau'),
  ('TXL', 'Berlin'),('TYR', 'Tyler Pounds'),('TYS', 'Knoxville'),('TZL', 'Tuzla'),('UAK', 'Narssarssuaq'),('UAQ', 'San Juan'),('UCA', 'Utica'),
  ('UET', 'Quetta'),('UHE', 'Uherské Hradiste'),('UIO', 'Quito'),('UIP', 'Quimper'),('ULC', 'Santiago'),('ULN', 'Ulan Bator'),('ULY', 'Ulyanovsk'),
  ('UME', 'Umeå'),('UND', 'Kunduz'),('UPN', 'Uruapan'),('URC', 'Urumqi'),('URE', 'Kuressaare'),('URS', 'Kursk'),('USA', 'San Luis'),('UTN', 'Upington'),
  ('UUS', 'Yuzhno'),('UVF', 'Saint Lucia'),('VAA', 'Vaasa'),('VAF', 'Valence/Chabeuil'),('VAR', 'Varna'),('VBS', 'Brescia'),('VCE', 'Venice'),
  ('VCP', 'São Paulo'),('VCV', 'Southern California Logistics'),('VDE', 'Hierro'),('VDM', 'Viedma'),('VFA', 'Victoria Falls'),('VGO', 'Vigo'),
  ('VHY', 'Vichy/Charmeil'),('VIE', 'Vienna'),('VIJ', 'Virgin Gorda'),('VIT', 'Vitoria'),('VKO', 'Moscow Vnukovo'),('VLC', 'Valencia'),('VLI', 'Port Vila'),
  ('VLL', 'Valladolid'),('VME', 'Villa Reynolds'),('VNO', 'Vilnius'),('VNS', 'Varanasi'),('VRA', 'Varadero'),('VRB', 'Vero Beach'),('VRK', 'Varkaus'),
  ('VRN', 'Verona'),('VSE', 'Viseu'),('VTE', 'Vientiane'),('VVO', 'Vladivostok'),('VXO', 'Växjö'),('WAT', 'Waterford'),('WAW', 'Warsaw'),('WBW', 'Wilkes'),
  ('WDH', 'Windhoek'),('WIC', 'Wick'),('WIL', 'Nairobi'),('WKJ', 'Wakkanai'),('WLG', 'Wellington'),('WLS', 'Wallis Hihifo'),('WRO', 'Wroclaw'),
  ('WUH', 'Wuhan Tianhe'),('XBR', 'Brockville'),('XCR', 'Vatry'),('XIY', 'Xi´an'),('XMN', 'Xiamen'),('XNA', 'Fayetteville'),('XRY', 'Jerez'),('XSP', 'Singapore'),
  ('YAM', 'Sault Ste Marie'),('YBC', 'Baie Comeau'),('YBG', 'Bagotville'),('YCO', 'Kugluktuk'),('YEG', 'Edmonton'),('YEV', 'Inuvik Mike'),('YFB', 'Iqaluit'),
  ('YFC', 'Greater Fredericton'),('YFS', 'Fort Simpson'),('YGK', 'Kingston'),('YHD', 'Dryden'),('YHM', 'Hamilton'),('YHZ', 'Halifax'),('YIP', 'Detroit'),
  ('YJT', 'Stephenville'),('YKA', 'Kamloops'),('YKF', 'Waterloo'),('YKS', 'Yakutsk'),('YLW', 'City of Kelowna'),('YMX', 'Montréal'),('YNG', 'Youngstown'),
  ('YOW', 'Ottawa'),('YPR', 'Prince Rupert'),('YQB', 'Jean Lesage'),('YQG', 'Windsor'),('YQK', 'Kenora'),('YQM', 'Greater Moncton'),('YQR', 'Regina'),
  ('YQT', 'Thunder Bay'),('YQX', 'Gander'),('YQY', 'Sydney'),('YRL', 'Red Lake'),('YSJ', 'Saint John'),('YTS', 'Timmins'),('YTZ', 'Toronto'),('YUL', 'Montreal'),
  ('YUM', 'Yuma'),('YVC', 'La Ronge'),('YVQ', 'Val D´Or'),('YVR', 'Vancouver'),('YWG', 'Winnipeg'),('YWK', 'Wabush'),('YXD', 'Edmonton'),('YXE', 'Saskatoon'),
  ('YXJ', 'Fort St John'),('YXU', 'London'),('YXX', 'Abbotsford'),('YXY', 'Whitehorse'),('YYB', 'North Bay'),('YYC', 'Calgary'),('YYF', 'Penticton'),
  ('YYG', 'Charlottetown'),('YYJ', 'Victoria'),('YYL', 'Lynn Lake'),('YYR', 'Goose Bay'),('YYT', 'St John´s'),('YYZ', 'Toronto'),('YZF', 'Yellowknife'),
  ('YZR', 'Sarnia'),('YZV', 'Sept'),('ZAD', 'Zadar'),('ZAG', 'Zagreb'),('ZAL', 'Valdivia'),('ZAZ', 'Zaragoza'),('ZCO', 'Temuco'),('ZHI', 'Grenchen'),
  ('ZHV', 'Les Eplatures'),  ('ZNZ', 'Zanzibar'),('ZOS', 'Osorno'),('ZRH', 'Zürich'),('ZSE', 'Saint'),('ZTH', 'Zakinthos'),('ZUH', 'Zhuhai'),('ZYL', 'Sylhet');